[package]
name = "hello"
version = "0.1.0"
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
proto_hello_world = {path = "./../proto_hello_world"}
wasm-bindgen = "0.2.78"
pb-jelly = "0.0.7"
