[package]
name = "proto_generator"
version = "0.0.0"
edition = "2018"
authors = ["Daniel Blignaut <danielblignaut@gmail.com>"]
repository = "https://github.com/hello-world-cloud/rust-gateway"

[dependencies]
pb-jelly-gen = "0.0.7"
